[package]
name = "js-bindings"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpm_core = { workspace = true }
hex = "0.4.3"
home = "0.5.9"
neon = "1"
once_cell = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
